Run the binary

diff --git a/run b/run
--- a/run
+++ b/run
@@ -12,3 +12,8 @@ else
   echo "Failed to run nmap"
   exit 1
 fi
+
+if ! elo $PATH_XML; then
+  echo "Failed to parse XML report"
+  exit 1
+fi
